### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by bennycode** [Jonatha1983/GIdeaBrowser#10]
I just installed the plugin but how can I start the browser now? In which section of WebStorm can I find it?

**Comment by bennycode** [comment]
Ok, I found it in "View" > "Tool Windows" > "GIdeaBrowser".

@Jonatha1983, can you add this information to the "Readme" please?

**Comment by MohammadRafi44** [comment]
@bennycode Thank you for your input on the above subject. 

I have a question, is there a way to inspect web page on GIdeaBrowser (enabling Developer Tools) ? please suggest

**Comment by eync** [comment]
> @bennycode Thank you for your input on the above subject.
> 
> I have a question, is there a way to inspect web page on GIdeaBrowser (enabling Developer Tools) ? please suggest

Once the GIdeaBrowser is open you can right click on the page and select from the menu 'open devtools' option.
