### ISSUE TITLE
Is there a way to refresh the browser window?

### ISSUE THREAD

**Issue by simensen** [Jonatha1983/GIdeaBrowser#11]
Hello! Excited to try this out for some pair programming sessions that require looking at a web page. I don't need much, and this seems to mostly satisfy my requirements except I don't seen an easy/obvious way to refresh the page. Is there a way to refresh a page either with a hotkey or via clicking a refresh button somewhere?

**Comment by Jonatha1983** [comment]
Hi @simensen - 
Currently there is no refresh - You can go to the url address + select + enter as a workaround.  
I am busy with other project so this project is currently not getting a high priority, you are more than welcome to contribute if want to implement a refresh button in a pr. 

Thanks
