### ISSUE TITLE
Suggestion：Open in browser

### ISSUE THREAD

**Issue by GarfieldCCC** [Jonatha1983/GIdeaBrowser#12]
Do you consider adding a "open in browser" function, when I right-click the webpage link in the IDE

**Comment by tintin10q** [comment]
This would be great

**Comment by Jonatha1983** [comment]
@GarfieldCCC  and @tintin10q 
Implemented in v1.0.21 - should be available once Jetbrains approve it (in the upcoming 1-2 days) 

I am closing the issue for now. 

![image](https://user-images.githubusercontent.com/3816566/147391525-12caabfc-1a6d-4482-a47b-306e2e0551f9.png)

**Comment by Jonatha1983** [comment]
Implemented in v1.0.21
