### ISSUE TITLE
Can we access the devtools settings?

### ISSUE THREAD

**Issue by wilcorrea** [Jonatha1983/GIdeaBrowser#17]

**Comment by Jonatha1983** [comment]
@wilcorrea you mean this?

![image](https://user-images.githubusercontent.com/3816566/127454049-b3ea82db-4c00-4ca5-9a5a-2a3cb88423dc.png)

**Comment by wilcorrea** [comment]
Yes @Jonatha1983, but here I can't see this option. Do I need to activate it?

![image](https://user-images.githubusercontent.com/803733/127497532-b7b4231e-dbbe-47c4-bd90-82ac9cbf6a76.png)

**Comment by wilcorrea** [comment]
The version that I have here:
![image](https://user-images.githubusercontent.com/803733/127498923-36b63b5d-7740-426b-af63-03d80f83a40b.png)

The settings that I can change
![image](https://user-images.githubusercontent.com/803733/127499068-27c669be-e723-4bed-acf2-ef6ee0e2d10c.png)

**Comment by Jonatha1983** [comment]
@wilcorrea maybe its some properties in the registry, look for cef property, mine are set like this: 
![image](https://user-images.githubusercontent.com/3816566/127542350-5e054926-5ab0-4290-9550-271c72598f02.png)


Please let me know the different

**Comment by wilcorrea** [comment]
sorry @Jonatha1983, but I don't know what is this registry. Can you clarify me about it? Where can I access it?

**Comment by Jonatha1983** [comment]
cmd + shift + A if it is a mac - search in the "actions search"

**Comment by Jonatha1983** [comment]
shift+shift = search everywhere 
and then type registry

**Comment by wilcorrea** [comment]
I ticked this one, I wanna try it

![image](https://user-images.githubusercontent.com/803733/127546523-2f43a518-1091-4582-b6ae-c349938d0136.png)

**Comment by wilcorrea** [comment]
After restart:
![image](https://user-images.githubusercontent.com/803733/127547662-4bcfa536-b44b-43c8-b9df-138a9d3c4fb6.png)

The right bottom still
![image](https://user-images.githubusercontent.com/803733/127547781-466b70da-e37d-4239-bad3-fd911a4dc814.png)

**Comment by Jonatha1983** [comment]
On which OS are you working on ?

**Comment by Jonatha1983** [comment]
Also what is the IJ version ?

**Comment by wilcorrea** [comment]
I am using Windows (a Windows 11 release preview)
![image](https://user-images.githubusercontent.com/803733/127552736-90f86d51-ff2b-4ea2-a298-bff88b914725.png)

I am using PhpStorm 2021.2
![image](https://user-images.githubusercontent.com/803733/127552807-e0eb09f7-9128-4ce3-ad38-cb9cfa9db6db.png)

```
PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Licensed to WILLIAM M V CORREA
Subscription is active until April 29, 2022.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2024M
Cores: 12
Registry: ide.browser.jcef.headless.enabled=true, run.processes.with.pty=TRUE
Non-Bundled Plugins: com.gafner.giv (1.0.14), com.github.b3er.idea.plugins.arc.browser (0.23), wide-task-browser (0.1.18), com.sburlyaev.terminal.plugin (0.4.4), com.wakatime.intellij.plugin (13.0.2), net.vektah.codeglance (1.5.4), one.util.ideaplugin.screenshoter (1.7), org.nik.presentation-assistant (1.0.9), com.intellij.plugin.adernov.powershell (2.0.7), MetricsReloaded (1.11.2), com.aurimasniekis.phppsr4namespacedetector (1.0.1), com.kalessil.phpStorm.phpInspectionsUltimate (3.0.12), de.espend.idea.php.annotation (8.0.0), me.elabee.idea.plugin.swoole (4.7.0), ru.vkurdin.idea.php.lambdafolding (0.3.0), fr.adrienbrault.idea.symfony2plugin (0.23.210), ru.adelf.idea.dotenv (2021.2)
```

**Comment by Jonatha1983** [comment]
```The Chrome DevTools, embedded into JCEF, can be used as a debugging and profiling tool. It’s active by default, so that a Chrome DevTools client can attach to it via the default port number - 9222. The port number can be configured with the following registry key:

ide.browser.jcef.debug.port=9222
```
https://plugins.jetbrains.com/docs/intellij/jcef.html#debugging

**Comment by Jonatha1983** [comment]
Ok found it:
https://plugins.jetbrains.com/docs/intellij/enabling-internal.html

**Comment by Jonatha1983** [comment]
I ll try to do it in the code for the user with a popup or something

**Comment by kobi26c** [comment]
Working for me after adding the idea.is.internal=true and restart

**Comment by wilcorrea** [comment]
Ok, it works. My WebStorm and PhpStorm are unexpected closing, but it works. Thanks for the help and congrats for the project

![image](https://user-images.githubusercontent.com/803733/127562619-7cb903b4-3bde-4591-819c-3435ca22e9f5.png)
