### ISSUE TITLE
[feature request] webpage zoom

### ISSUE THREAD

**Issue by wizzard0** [Jonatha1983/GIdeaBrowser#19]
would be very useful to be able to zoom out, as sidebar panels are often small

**Comment by Jonatha1983** [comment]
Yes will add this option in the next release

**Comment by Jonatha1983** [comment]
@wizzard0  implemented in v1.0.22 - waiting for Jetbrains approval, probably you will be able to see it till the end of the week.

**Comment by Jonatha1983** [comment]
Implemented in v1.0.22
