### ISSUE TITLE
might be a simple question, but how do I enable GideaBrowser as a default runner on WebStorm?

### ISSUE THREAD

**Issue by qrrabbit** [Jonatha1983/GIdeaBrowser#42]
![image](https://user-images.githubusercontent.com/3392954/160466990-c7d91a97-5752-4d1e-aca4-361fb2a025df.png)
This image is a screenshot of WebStorm Preferences->Tools-Web Browsers and Preview.

There's an option to Default Browser with Custom Path:
![image](https://user-images.githubusercontent.com/3392954/160467347-32b53313-ef02-495a-a92e-bf0bb9b2bb1e.png)

But what is the path, on MacOS? Please advise,

Thank you,

**Comment by lucashooten** [comment]
> This is not related to the plugin

Also have this question. If it's not supported, could you clarify? If it is, could you help us understand where to point (or how to set) for default browser?
