### ISSUE TITLE
Plugin Not Compatible With New 2022.1 Version

### ISSUE THREAD

**Issue by buzzokas** [Jonatha1983/GIdeaBrowser#43]
![image](https://user-images.githubusercontent.com/18693587/167096564-54c3af00-3bb9-41e0-9127-8f1ceae34457.png)

**Comment by Jonatha1983** [comment]
@buzzokas thanks we know hope to find time the upcoming weekend to release new version.

**Comment by Jonatha1983** [comment]
Sorry about A very long weekend. Closing should work now.
