### ISSUE TITLE
Intellij Compatibility - Build #IU-222.2964.55 (2022.2)

### ISSUE THREAD

**Issue by Les-Linux** [Jonatha1983/GIdeaBrowser#44]

**Comment by Les-Linux** [comment]
Hello,

First off.. great Tool :). Is there a chance of releasing a version compatible with 2022.2 ? I am currently running Build #IU-222.2964.55 and being able to use the GIdea-Browser would make life a little easier.

Thanks and best regards.

Les

**Comment by Les-Linux** [comment]
With a small adjustment, I managed to get it to install however bookmarks are not stored after restarting IntelliJ as an fyi. I would guess with the proper change implementation that bookmarks will be fine.

**Comment by Jonatha1983** [comment]
@Les-Linux Done I am closing. 
About the bookmarks if you want to contribute will be great 🙏 
If not all good! I think I will find the time on one of the next releases...

Thanks
