### ISSUE TITLE
2023.1 Support

### ISSUE THREAD

**Issue by blowsie** [Jonatha1983/GIdeaBrowser#58]
![image](https://user-images.githubusercontent.com/308572/232019011-dc88b787-029c-473d-b054-7a7ac56a1e19.png)

**Comment by blowsie** [comment]
https://github.com/Jonatha1983/GIdeaBrowser/pull/56

**Comment by Jonatha1983** [comment]
Done

**Comment by blowsie** [comment]
Still shows the same for me

**Comment by blowsie** [comment]
Ok, now its working. Thank you!
